apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    server: https://localhost:10000
    insecure-skip-tls-verify: true
  name: private-tunnel
users:
- name: aws-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - eks
      - get-token
      - --cluster-name
      - 10-minute-private-eks-con # Use the short name for the token generator
      - --region
      - us-east-1
contexts:
- context:
    cluster: private-tunnel
    user: aws-user
  name: private-tunnel-context
current-context: private-tunnel-context
